[versions]
minecraft = "1.6.4"
yarn_build = "535"
fabric_loader = "0.15.7"
loom = "1.5-SNAPSHOT"
legacy-looming = "1.5-SNAPSHOT"
vineflower = "1.10.0-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
legacy_looming = { id = "legacy-looming", version.ref = "legacy-looming" }
